name: Build and Push Docker Image to DockerHub

# Ce workflow est déclenché par un push sur la branche 'main'
on:
  push:
    branches:
      - main  # Vous pouvez remplacer 'main' par la branche que vous utilisez

jobs:
  build:
    # L'environnement où le job s'exécute
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Vérifier le code source
    - name: Check out repository
      uses: actions/checkout@v2

    # Étape 2: Configurer Docker Buildx (utile pour l'optimisation des builds Docker
    uses: docker/setup-buildx-action@v1

    # Étape 3: Authentification DockerHub
    # Utilise les secrets pour se connecter à DockerHub de manière sécurisée
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.birama2001}}  # Remplacez par votre nom d'utilisateur DockerHub
        password: ${{ secrets.token}}  # Remplacez par votre mot de passe DockerHub ou votre token d'accès

    # Étape 4: Construire l'image Docker
    - name: Build Docker
    run: docker build -t ${{ secrets.birama2001 }}/basic-docker-project:latest .

    # Étape 5: Pousser l'image vers DockerHub
    - name: Push Docker image
      run: docker push ${{ secrets.birama2001 }}/basic-docker-project:latest

